### ISSUE TITLE
Failure in Cypress pre-release when running through this test repo.

### ISSUE THREAD

**Issue by jennifer-shehane** [bahmutov/cypress-vue-unit-test#286]
This repo is failing in `develop` branch of Cypress - our pre-release: https://circleci.com/gh/cypress-io/cypress-test-example-repos/91890

Seems that every spec file is failing with the same error:

```                                                                                                   
  Running:  ajax-list-spec.js                                                              (1 of 17)
Trace: The node type SpreadProperty has been renamed to SpreadElement
    at Object.isSpreadProperty (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/types/lib/validators/generated/index.js:4512:11)
    at hasSpread (/tmp/cypress-vue-unit-testJJtmOf/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/tmp/cypress-vue-unit-testJJtmOf/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:66:12)
Trace: The node type SpreadProperty has been renamed to SpreadElement
    at Object.isSpreadProperty (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/types/lib/validators/generated/index.js:4512:11)
    at hasSpread (/tmp/cypress-vue-unit-testJJtmOf/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/tmp/cypress-vue-unit-testJJtmOf/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:66:12)
Trace: The node type SpreadProperty has been renamed to SpreadElement
    at Object.isSpreadProperty (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/types/lib/validators/generated/index.js:4512:11)
    at hasSpread (/tmp/cypress-vue-unit-testJJtmOf/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/tmp/cypress-vue-unit-testJJtmOf/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/tmp/cypress-vue-unit-testJJtmOf/node_modules/@babel/traverse/lib/path/context.js:97:18)
```

**Comment by bahmutov** [comment]
Let's see - I have removed the spread plugin, since it is no longer necessary https://travis-ci.org/github/bahmutov/cypress-vue-unit-test/builds/672577255

But the failure might be some XHR flake. If it keeps failing I will skip this test.
